version: "3"

services:
    node:
        build: .
        command: yarn dev
        container_name: chiquezi-node
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: chiquezi-mysql
        restart: always
        ports:
            - 3310:3306
        environment:
            MYSQL_ROOT_PASSWORD: ok
        volumes:
            - ./mysql-volume:/var/lib/mysql
            - ./mysql-initial:/docker-entrypoint-init.d:ro
volumes:
    mysql-volume:
